#!/bin/bash
set -eux -o pipefail

: "${GITHUB_REF}" # refs/pull/N/merge
: "${GITHUB_BASE_REF}"
: "${GITHUB_HEAD_REF}"

git config user.name kubebuilder-updates
git config user.email 41898282+github-actions[bot]@users.noreply.github.com

# Fetch the versions
git fetch origin --depth=1 "${GITHUB_BASE_REF}:${GITHUB_BASE_REF}"
old_version="$(git show "${GITHUB_BASE_REF}:.kubebuilder-version")"
new_version="$(cat .kubebuilder-version)"

# Fetch the commit
git fetch origin --depth=10 "${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}"
commit_sha="$(git log -1 --grep 'Generated by GitHub Actions' --format=%H "${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}")"

pull_number="$(echo "${GITHUB_REF}" | cut -d/ -f3)"
export README_SECTION="
### Update kubebuilder from ${old_version} to ${new_version}

To apply the patch of https://github.com/int128/kubebuilder-updates/pull/${pull_number}/commits/${commit_sha},

\`\`\`sh
# Fetch the diff
git fetch https://github.com/int128/kubebuilder-updates ${commit_sha}

# Apply the patch
git checkout -b update-kubebuilder-${new_version}
git cherry-pick ${commit_sha}
\`\`\`

You may need to resolve conflicts.

\`\`\`sh
git commit -m 'Update kubebuilder from ${old_version} to ${new_version}'
gh pr create -f
\`\`\`

"

# Prepend the section to README.md
if [ "${commit_sha}" ]; then
  perl -i -ne 'print; if ($_ =~ /<!-- SECTION -->/) { print $ENV{"README_SECTION"} }' README.md
fi
