name: docker

on:
  pull_request:
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - internal/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - internal/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@0b4582921757b6145fd7fab8156c725b28e1c2b8 # v1.31.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: make -C e2e_test cluster

      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          # set outputs.tags to single tag
          flavor: latest=false
      - uses: int128/wait-for-docker-image-action@4975bd239c55b16ec86bbcca9cab53ac056f8e07 # v1.8.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test deploy
        env:
          CONTROLLER_IMAGE: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test logs-controller
        if: always()
