name: e2e-test

on:
  pull_request:
    paths:
      - .github/workflows/e2e-test.yaml
      - go.*
      - '**/*.go'
      - Dockerfile
      - Makefile
      - config/**
      - e2e_test/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/e2e-test.yaml
      - go.*
      - '**/*.go'
      - Dockerfile
      - Makefile
      - config/**
      - e2e_test/**

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: make -C e2e_test cluster

      - uses: int128/wait-for-workflows-action@v1
        with:
          filter-workflow-names: docker

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
      - run: make -C e2e_test deploy
        env:
          CONTROLLER_IMAGE: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test logs-controller
        if: always()
