name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@2c81802e1fca8d9142d5b351672694459f998026 # v1.2.0
    permissions:
      contents: write
      pull-requests: write
    with:
      go-version-file: go.mod
      cache-dependency-path: go.sum
