name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - main.go
      - api/**.go
      - controllers/**.go
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - main.go
      - api/**.go
      - controllers/**.go

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@v1
    with:
      go-version: 1.20.2
      golangci-lint-version: v1.52.1
