name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@v1
    with:
      go-version: 1.21.5
      golangci-lint-version: v1.55.2
