name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'

jobs:
  go:
    uses: int128/kubebuilder-workflows/.github/workflows/go.yaml@e4ad31a438f188f70bde87827a8dbe466e623dea # v1.5.0
    permissions:
      contents: write
      pull-requests: write
    with:
      go-version-file: go.mod
      cache-dependency-path: go.sum
      ignore-lint-error: true
